src/apps/accounts/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url
from accounts.views import user_login as login, user_logout as logout


urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),

]

src/apps/dictionaries/category/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from dictionaries.category.views import (CategoriesListView, CategoriesCreateView,
                                         CategoriesDetailView)
from dictionaries.category.views import CategoriesUpdateView, CategoriesDeleteView

urlpatterns = [
    url(r'^$',
        CategoriesListView.as_view(),
        name='categories-list'
        ),
    url(
        r'^add/$',
        CategoriesCreateView.as_view(),
        name='categories-add'
    ),
    url(
        r'^(?P<category>[-\w]+)/$',
        CategoriesDetailView.as_view(),
        name='categories-detail'
    ),
    url(
        r'^(?P<category>[-\w]+)/edit/$',
        CategoriesUpdateView.as_view(),
        name='categories-edit'
    ),
    url(
        r'^(?P<category>[-\w]+)/delete/$',
        CategoriesDeleteView.as_view(),
        name='categories-delete'
    ),
    url(
        r'^(?P<category>[-\w]+)/types/',
        include('dictionaries.type.urls')
    ),

]

src/apps/dictionaries/items/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from dictionaries.items.views import DicItemsListView, DicItemsCreateView, \
    DicItemsDetailView, DicItemsUpdateView, DicItemsDeleteView


urlpatterns = [
    url(r'^$', DicItemsListView.as_view(), name='items-list'),
    url(r'^add/$', DicItemsCreateView.as_view(), name='items-add'),
    url(r'^(?P<dictionary_id>[0-9]+)/$', DicItemsDetailView.as_view(), name='items-detail'),
    url(r'^(?P<dictionary_id>[0-9]+)/edit/$', DicItemsUpdateView.as_view(), name='items-edit'),
    url(r'^(?P<dictionary_id>[0-9]+)/delete/$', DicItemsDeleteView.as_view(), name='items-delete'),
]

src/apps/history/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from history.views import HistoryAddView, HistoryUpdateView, HistoryDeleteView


urlpatterns = [
    url(
        r'^(?P<param>[-\w]+)/history/add/$',
        HistoryAddView.as_view(),
        name='history-add'
    ),
    url(
        r'^(?P<param>[-\w]+)/history/(?P<history_id>[0-9]+)/edit/$',
        HistoryUpdateView.as_view(),
        name='history-edit'
    ),
    url(
        r'^(?P<param>[-\w]+)/history/(?P<history_id>[0-9]+)/delete/$',
        HistoryDeleteView.as_view(),
        name='history-delete'
    )
]

src/apps/reports/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from reports.views import reports_view, reports_file


urlpatterns = [
    url(r'^$', reports_view, name='index'),
    url(r'^get/$', reports_file, name="get"),
]

src/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from common.dashboard import DashboardView
from common.views import status_view
from loader.views import upload

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^$', login_required(DashboardView.as_view()), name='dashboard'),
    url(r'', include('accounts.urls', namespace='accounts')),

    url(r'^children/', include('children.urls', namespace='children')),
    url(r'^dictionaries/', include('dictionaries.urls', namespace='dictionaries')),
    url(r'^upload/$', login_required(upload), name='loader'),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^status/$', status_view, name="status"),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/dictionaries/models.py
from django.db import models
from django.db.models import permalink
from common.models import NameUniqueModel, NameSlugUniqueModel


class Category(NameSlugUniqueModel):
    pass

    class Meta:
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def save(self, *args, **kwargs):
        if self.position == 0:
            self.position = Category.objects.all().count() + 1
        return super(Category, self).save(*args, **kwargs)

    @permalink
    def get_absolute_url(self):
        return 'dictionaries:categories-detail', None, {'category': self.slug}


class DictionariesType(NameSlugUniqueModel):
    category = models.ForeignKey(Category, verbose_name='Категория')

    class Meta:
        db_table = 'types'
        verbose_name = 'Тип справочника'
        verbose_name_plural = 'Типы справочников'

    def save(self, *args, **kwargs):
        if self.position == 0:
            self.position = DictionariesType.objects.filter(category=self.category).count() + 1
        return super(DictionariesType, self).save(*args, **kwargs)

    @permalink
    def get_absolute_url(self):
        return 'dictionaries:types-detail', \
               None, \
               {
                   'category': self.category.slug,
                   'dictionary_type': self.slug
               }


class Dictionary(NameUniqueModel):
    INSTITUTION_TYPE_CHOICE = (
        (0, 'Дошкольное'),
        (1, 'Школьное'),)

    type = models.ForeignKey(DictionariesType, verbose_name='Тип')
    institution_type = models.IntegerField('Тип учреждения', blank=True, null=True,
                                           choices=INSTITUTION_TYPE_CHOICE)

    class Meta:
        db_table = 'dictionaries'
        verbose_name = 'Справочник'
        verbose_name_plural = 'Справочники'

    @permalink
    def get_absolute_url(self):
        return 'dictionaries:items-detail', \
               None, \
               {
                   'category': self.type.category.slug,
                   'dictionary_type': self.type.slug,
                   'dictionary_id': self.id
               }

src/apps/accounts/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST['username'],
                                password=request.POST['password'])
            if user is not None:
                if user.is_active:
                    django_login(request, user)
                    return redirect('children:list')
    else:
        form = AuthenticationForm()
    return render_to_response('accounts/login.html', {
        'form': form,
    }, context_instance=RequestContext(request))


def user_logout(request):
    auth.logout(request)
    return redirect('children:list')

src/apps/children/views.py
import json
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView, TemplateView
from django.views.generic.base import ContextMixin
from django_datatables_view.base_datatable_view import BaseDatatableView

from children.forms import ChildForm
from children.forms import FilterChildrenForm
from children.models import Child
from common.utils import get_param_on_date, get_qs_by_param_name, get_list_names_in_param
from history.models import Param


class ChildrenBaseView(LoginRequiredMixin, ContextMixin):
    model = Child
    context_object_name = 'children'
    pk_url_kwarg = 'child_id'


class ChildBaseView(ChildrenBaseView):
    context_object_name = 'child'


class ChildrenTemplateView(ChildrenBaseView, TemplateView):
    template_name = 'children/children_list.html'

    def get_context_data(self, **kwargs):
        context = super(ChildrenTemplateView, self).get_context_data(**kwargs)
        context['filter_form'] = FilterChildrenForm
        return context


class ChildrenCreateView(ChildBaseView, CreateView):
    template_name = 'children/children_edit.html'
    form_class = ChildForm

    def get_context_data(self, **kwargs):
        context = super(ChildrenCreateView, self).get_context_data(**kwargs)
        context['back_url'] = self.request.META.get('HTTP_REFERER', reverse_lazy('children:list'))
        return context


class ChildrenDetailView(ChildBaseView, DetailView):
    template_name = 'children/children_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ChildrenDetailView, self).get_context_data(**kwargs)
        context['params'] = Param.objects.all()
        return context


class ChildrenUpdateView(ChildBaseView, UpdateView):
    template_name = 'children/children_edit.html'
    form_class = ChildForm

    def get_context_data(self, **kwargs):
        context = super(ChildrenUpdateView, self).get_context_data(**kwargs)
        context['back_url'] = \
            self.request.META.get('HTTP_REFERER',
                                  reverse_lazy('children:detail',
                                               kwargs={'children_id': self.object.id}))
        return context


class ChildrenDeleteView(ChildBaseView, DeleteView):

    def get_success_url(self):
        return reverse_lazy('children:list')


class ChildListJson(BaseDatatableView):
    order_columns = ['last_name', 'birthday']

    def __init__(self):
        super(ChildListJson, self).__init__()
        self.date = datetime.now()

    def get_initial_queryset(self):
        return Child.objects.all()

    def filter_queryset(self, qs):
        search = self.request.GET.get(u'search[value]', None)
        _filter = self.request.GET.get(u'columns[0][search][value]', None)

        if _filter:
            children_list = []
            filter_params = json.loads(_filter)

            health_states = []
            mode_health_states = 0
            parents_status = []
            mode_parents_status = 0

            if 'date' in filter_params:
                filter_params['date'] = datetime.strptime(
                    filter_params['date'],
                    '%Y-%m-%dT%H:%M:%S.%fZ'
                )
                self.date = filter_params['date']
            if 'institution' in filter_params:
                qs = get_qs_by_param_name(name='institution', qs=qs, **filter_params)
            if 'group' in filter_params:
                qs = get_qs_by_param_name(name='group', qs=qs, **filter_params)
            if 'grade' in filter_params:
                qs = get_qs_by_param_name(name='grade', qs=qs, **filter_params)
            if 'health_states'in filter_params:
                health_states = get_list_names_in_param(
                    filter_params['health_states'],
                    param='health'
                )
                mode_health_states = filter_params['mode_health_states']
                qs = get_qs_by_param_name(name='health_states', qs=qs, **filter_params)
            if 'parents_status' in filter_params:
                parents_status = get_list_names_in_param(
                    filter_params['parents_status'],
                    param='parents'
                )
                mode_parents_status = filter_params['mode_parents_status']
                qs = get_qs_by_param_name(name='parents_status', qs=qs, **filter_params)

            for child in qs:
                children_list.append([
                    child.id,
                    get_param_on_date(child, 'health', 'health_list', filter_params['date']),
                    get_param_on_date(child, 'parents', 'parents_list', filter_params['date']),
                ])

            if health_states and mode_health_states != 0:

                _children_list = children_list.copy()
                children_list.clear()

                if mode_health_states == 2:

                    _condition = ', '.join([states for states in health_states])
                    for _children in _children_list:
                        if _children[1] == _condition:
                            children_list.append(_children)
                else:

                    _condition = [states for states in health_states]
                    for _children in _children_list:

                        if set(_condition) <= set(_children[1].split(', ')):
                            children_list.append(_children)

                qs = qs.filter(pk__in=set([child[0] for child in children_list]))

            if parents_status and mode_parents_status != 0:

                _children_list = children_list.copy()
                children_list.clear()

                if mode_parents_status == 2:

                    _condition = ', '.join([status for status in parents_status])
                    for _children in _children_list:
                        if _children[2] == _condition:
                            children_list.append(_children)
                else:

                    _condition = [status for status in parents_status]
                    for _children in _children_list:

                        if set(_condition) <= set(_children[2].split(', ')):
                            children_list.append(_children)

                qs = qs.filter(pk__in=list(set([child[0] for child in children_list])))

        if search:

            if search.find(' ') != -1:
                filter_last_name = search.split(' ')[0]
                filter_first_name = search.split(' ')[1]
                qs = qs.filter(last_name__istartswith=filter_last_name,
                               first_name__istartswith=filter_first_name)
            else:
                qs = qs.filter(last_name__istartswith=search)

        return qs

    def prepare_results(self, qs):

        json_data = []

        for item in qs:
            json_data.append(
                {'full_name': item.get_full_name(),
                 'link': item.get_absolute_url(),
                 'age': item.get_age(date=self.date)
                 }
            )
        return json_data

src/apps/common/views.py
# -*- coding: utf-8 -*-
import json

import django_rq
from django.http import HttpResponse
from rq.job import Job


def status_view(request):
    ret = {}
    job_id = request.GET.get('job_id')
    redis_conn = django_rq.get_connection()
    job = Job.fetch(job_id, redis_conn)
    if job.is_finished:
        ret = {'status': 'finished'}
    elif job.is_queued:
        ret = {'status': 'in-queue'}
    elif job.is_started:
        ret = {'status': 'waiting'}
    elif job.is_failed:
        ret = {'status': 'failed'}

    return HttpResponse(json.dumps(ret), content_type="application/json")

src/apps/dictionaries/category/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import ContextMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from dictionaries.models import Category
from django.core.urlresolvers import reverse_lazy
from dictionaries.views import EDIT_TEMPLATE, get_template

template = 'dictionaries/category/'


class CategoriesBaseView(LoginRequiredMixin, ContextMixin):
    model = Category
    context_object_name = 'category'
    slug_url_kwarg = 'category'


class CategoriesListView(CategoriesBaseView, ListView):
    context_object_name = 'categories'
    template_name = get_template(template, 'list')

    def get_queryset(self):
        return Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CategoriesListView, self).get_context_data(**kwargs)
        context['add_category'] = reverse_lazy('dictionaries:categories-add')
        return context


class CategoriesCreateView(CategoriesBaseView, CreateView):
    template_name = EDIT_TEMPLATE
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(CategoriesCreateView, self).get_context_data(**kwargs)
        context['back_url'] = self.request.META.get(
            'HTTP_REFERER', reverse_lazy('dictionaries:categories-list'))
        return context


class CategoriesDetailView(CategoriesBaseView, DetailView):
    template_name = get_template(template, 'detail')


class CategoriesUpdateView(CategoriesBaseView, UpdateView):
    template_name = EDIT_TEMPLATE
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(CategoriesUpdateView, self).get_context_data(**kwargs)
        context['back_url'] = \
            self.request.META.get('HTTP_REFERER',
                                  reverse_lazy('dictionaries:categories-detail',
                                               kwargs={'category': self.object.slug}))
        return context


class CategoriesDeleteView(CategoriesBaseView, DeleteView):
    pass

    def get_success_url(self):
        return reverse_lazy('dictionaries:categories-list')

src/apps/dictionaries/views.py
from django.views.generic.base import TemplateView
from dictionaries.models import Category

EDIT_TEMPLATE = 'dictionaries/edit.html'


def get_template(template, name):
    return '{}/{}.html'.format(template, name)


class DictionariesView(TemplateView):
    template_name = 'dictionaries/index.html'

    def get_context_data(self, **kwargs):
        context = super(DictionariesView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context

src/templates/dictionaries/address.html
{% extends 'dictionaries/layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="list-group">
          <a href="{% url 'locality:list' %}" class="list-group-item">Населенные пункты</a>
        </div>
    </div>

     <div class="col-md-6">
        <div class="list-group">
          <a href="{% url 'streets:list' %}" class="list-group-item">Улицы</a>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/dictionaries/dictionaries.html
{% extends 'dictionaries/layout.html' %}

{% block content %}
<div class="row">

    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'education' %}" class="list-group-item active">Образование</a>
          <a href="{% url 'institutions:list' %}" class="list-group-item">Учреждения</a>
          <a href="{% url 'groups:list' %}" class="list-group-item">Возрастные группы</a>
          <a href="{% url 'grades:list' %}" class="list-group-item">Классы</a>
        </div>
    </div>

    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'address' %}" class="list-group-item active">Адреса</a>
          <a href="{% url 'locality:list' %}" class="list-group-item">Населенные пункты</a>
          <a href="{% url 'streets:list' %}" class="list-group-item">Улицы</a>
        </div>
    </div>

    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'secondary' %}" class="list-group-item active">Дополнительные сведения</a>
          <a href="{% url 'health:list' %}" class="list-group-item">Состояния здоровья</a>
          <a href="{% url 'parents:list' %}" class="list-group-item">Статусы родителей</a>
        </div>
    </div>

</div>
{% endblock content %}

src/templates/dictionaries/edit.html
{% extends 'dictionaries/layout.html' %}
{% load bootstrap  %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-body">
             <form class="form-horizontal" method="post">
                 {% csrf_token %}
                 {{ form | bootstrap_horizontal }}
                 <div class="pull-right">
                    <a href="{{ back_url }}" class="btn btn-default">Отменить</a>
                    <button type="submit" class="btn btn-primary">Выполнить</button>
                 </div>
             </form>
            </div>
        </div>
    </div>
</div>
{% endblock content  %}

src/templates/dictionaries/education.html
{% extends 'dictionaries/layout.html' %}

{% block content %}
<div class="row">

            <div class="col-md-4">
                <div class="list-group">
                  <a href="{% url 'institutions:list' %}" class="list-group-item">Учреждения</a>
                </div>
            </div>

             <div class="col-md-4">
                <div class="list-group">
                  <a href="{% url 'groups:list' %}" class="list-group-item">Возрастные группы</a>
                </div>
            </div>

             <div class="col-md-4">
                <div class="list-group">
                  <a href="{% url 'grades:list' %}" class="list-group-item">Классы</a>
                </div>
            </div>

          </div>
{% endblock content %}

src/templates/dictionaries/index.html
{% extends 'dictionaries/layout.html' %}

{% block page_header %}
            {{ block.super }}
            <div class="pull-right">
            <a href="{% url 'dictionaries:categories-add' %}" class="btn btn-primary">Добавить категорию</a>
        </div>
{% endblock page_header %}

{% block content %}

    {% for category in categories %}
        {% cycle '<div class="row">' '' ''%}
            <div class="col-md-4">
                 <div class="list-group">
                     <a href="{% url 'dictionaries:categories-detail' category.slug %}"
                        class="list-group-item active">{{ category.name }}</a>
                     {% for type in category.dictionariestype_set.all %}
                        <a href="{% url 'dictionaries:items-list' category.slug type.slug %}"
                           class="list-group-item">{{ type }}</a>
                     {% endfor %}
                 </div>
            </div>
        {% cycle '' '' '</div>' %}
    {% endfor %}

{% endblock content %}

src/templates/dictionaries/layout.html
{% extends 'layout/content.html' %}
{% load sitetree %}

{% block title %}{% sitetree_page_title from "dictionaries" %} |  {{ block.super }}{% endblock title %}

{% block page_header %}
    {% sitetree_page_title from "dictionaries" %}
{% endblock page_header %}

{% block breadcrumbs %}
    {% sitetree_breadcrumbs from "dictionaries" template "layout/breadcrumbs.html" %}
{% endblock breadcrumbs %}

src/templates/dictionaries/secondary.html
{% extends 'dictionaries/layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="list-group">
          <a href="{% url 'health:list' %}" class="list-group-item">Состояния здоровья</a>
        </div>
    </div>

     <div class="col-md-6">
        <div class="list-group">
          <a href="{% url 'parents:list' %}" class="list-group-item">Статусы родителей</a>
        </div>
    </div>
</div>
{% endblock content %}