src/apps/accounts/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url
from accounts.views import user_login as login, user_logout as logout


urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),

]

src/apps/children/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from children.views import ChildrenTemplateView, ChildrenDetailView, ChildrenUpdateView
from children.views import ChildrenCreateView, ChildrenDeleteView, ChildListJson


urlpatterns = [
    url(r'^$', ChildrenTemplateView.as_view(), name='list'),
    url(r'^add/$', ChildrenCreateView.as_view(), name='add'),

    url(r'^(?P<child_id>[0-9]+)/$', ChildrenDetailView.as_view(), name='detail'),
    url(r'^(?P<child_id>[0-9]+)/edit/$', ChildrenUpdateView.as_view(), name='edit'),
    url(r'^(?P<child_id>[0-9]+)/delete/$', ChildrenDeleteView.as_view(), name='delete'),

    url(r'^(?P<child_id>[0-9]+)/params/', include('history.urls')),

    url(r'^data-table/$', login_required(ChildListJson.as_view()), name='child_list_json')
]

src/apps/history/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from history.views import HistoryAddView, HistoryUpdateView, HistoryDeleteView


urlpatterns = [
    url(
        r'^(?P<param>[-\w]+)/history/add/$',
        HistoryAddView.as_view(),
        name='history-add'
    ),
    url(
        r'^(?P<param>[-\w]+)/history/(?P<history_id>[0-9]+)/edit/$',
        HistoryUpdateView.as_view(),
        name='history-edit'
    ),
    url(
        r'^(?P<param>[-\w]+)/history/(?P<history_id>[0-9]+)/delete/$',
        HistoryDeleteView.as_view(),
        name='history-delete'
    )
]

src/apps/reports/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from reports.views import reports_view, reports_file


urlpatterns = [
    url(r'^$', reports_view, name='index'),
    url(r'^get/$', reports_file, name="get"),
]

src/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from common.dashboard import DashboardView
from common.views import status_view
from loader.views import upload

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^$', login_required(DashboardView.as_view()), name='dashboard'),
    url(r'', include('accounts.urls', namespace='accounts')),

    url(r'^children/', include('children.urls', namespace='children')),
    url(r'^dictionaries/', include('dictionaries.urls', namespace='dictionaries')),
    url(r'^upload/$', login_required(upload), name='loader'),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^status/$', status_view, name="status"),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/history/models.py
from django.db import models
from common.models import NameSlugUniqueModel
from history.base_models import HistoryParamsBase
from dictionaries.models import Dictionary
from datetime import timedelta
from transfer.models import Step


class Param(NameSlugUniqueModel):
    pass

    class Meta:
        db_table = 'param'
        verbose_name = 'Параметр'
        verbose_name_plural = 'Параметры'
        ordering = ['position', ]

    def save(self, *args, **kwargs):
        if self.position == 0:
            self.position = Param.objects.all().count() + 1
        return super(Param, self).save(*args, **kwargs)


class ParamHistory(HistoryParamsBase):
    BOOL_CHOICES = (
        (True, 'Да'),
        (False, 'Нет')
    )

    parameter = models.ForeignKey(Param, verbose_name='Параметр')
    institution = models.ForeignKey(Dictionary, verbose_name='Учреждение',
                                    related_name="history_institution", blank=True, null=True)
    group = models.ForeignKey(Dictionary, verbose_name='Группа',
                              related_name="history_group", blank=True, null=True)
    grade = models.ForeignKey(Dictionary, verbose_name='Класс',
                              related_name="history_grade", blank=True, null=True)
    parents_status = models.ManyToManyField(Dictionary, verbose_name='Статус семьи',
                                            related_name="history_parents_status", blank=True)
    health_states = models.ManyToManyField(Dictionary, verbose_name='Состояние здоровья',
                                           related_name="history_health_states", blank=True)
    risk_group = models.BooleanField(choices=BOOL_CHOICES, verbose_name='Группа риска')
    note = models.CharField('Примечание', max_length=256, blank=True, null=True)

    class Meta:
        db_table = 'param_history'
        verbose_name = 'Истории параметров'
        verbose_name_plural = 'История параметров'
        ordering = ['-first_date', '-last_date', ]

    def __str__(self):
        if self.last_date:
            return 'c {} по {} - {}'.format(self.first_date, self.last_date, self.parameter.name)
        else:
            return 'c {} по н.в. - {}'.format(self.first_date, self.parameter.name)

    def get_health_states(self):
        return ', '.join([val.name for val in self.health_states.all()])

    def get_parents_status(self):
        return ', '.join([val.name for val in self.parents_status.all()])

    def save(self, *args, **kwargs):

        one_day = timedelta(days=1)

        all_history_list = ParamHistory.objects.filter(child=self.child). \
            filter(parameter__slug=self.parameter.slug).order_by('first_date')

        open_history_list = all_history_list.filter(last_date=None)

        if len(open_history_list):
            for open_history in open_history_list:
                if open_history.first_date <= self.first_date - one_day:
                    open_history.last_date = self.first_date - one_day
                    open_history.save()

        return super(ParamHistory, self).save(*args, **kwargs)

    def get_step(self):

        _filter = None
        step = 0

        if self.group:
            _filter = self.group
        if self.grade:
            _filter = self.grade
        if _filter:
            try:
                step = Step.objects.get(level_id=_filter).position
            except Step.DoesNotExist:
                step = 0
        return step

    def get_next_step_value(self, slug):
        step = Step.objects.get(position=self.get_step())

        try:
            next_step = Step.objects.get(position=step.get_next_position())

            if next_step.level.type.slug == slug:
                return next_step.level
            else:
                return None
        except Step.DoesNotExist:
            return None

    def get_institution_next_step(self):
        position = self.get_step()

        if position == 17 or position == 0:
            return None
        else:
            return self.institution

    def set_next_step(self, date):

        try:
            parameter = Param.objects.get(slug='education')

            ParamHistory.objects.create(
                first_date=date,
                parameter=parameter,
                child=self.child,
                institution=self.get_institution_next_step(),
                group=self.get_next_step_value(slug='groups'),
                grade=self.get_next_step_value(slug='grades'),
                risk_group=0
            )

        except Param.DoesNotExist:
            pass

src/apps/reports/forms.py
# -*- coding: utf-8 -*-
from django import forms

from common.forms import FilterForm


class ReportsForm(FilterForm):

    field_order = ['report_date', 'report_type', ]

    REPORT_CHOICES = (
        (1, 'Список'),
        (2, 'Свод')
    )
    report_type = forms.ChoiceField(label='Тип отчета', choices=REPORT_CHOICES)

src/apps/accounts/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST['username'],
                                password=request.POST['password'])
            if user is not None:
                if user.is_active:
                    django_login(request, user)
                    return redirect('children:list')
    else:
        form = AuthenticationForm()
    return render_to_response('accounts/login.html', {
        'form': form,
    }, context_instance=RequestContext(request))


def user_logout(request):
    auth.logout(request)
    return redirect('children:list')

src/apps/children/views.py
import json
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView, TemplateView
from django.views.generic.base import ContextMixin
from django_datatables_view.base_datatable_view import BaseDatatableView

from children.forms import ChildForm
from children.forms import FilterChildrenForm
from children.models import Child
from common.utils import get_param_on_date, get_qs_by_param_name, get_list_names_in_param
from history.models import Param


class ChildrenBaseView(LoginRequiredMixin, ContextMixin):
    model = Child
    context_object_name = 'children'
    pk_url_kwarg = 'child_id'


class ChildBaseView(ChildrenBaseView):
    context_object_name = 'child'


class ChildrenTemplateView(ChildrenBaseView, TemplateView):
    template_name = 'children/children_list.html'

    def get_context_data(self, **kwargs):
        context = super(ChildrenTemplateView, self).get_context_data(**kwargs)
        context['filter_form'] = FilterChildrenForm
        return context


class ChildrenCreateView(ChildBaseView, CreateView):
    template_name = 'children/children_edit.html'
    form_class = ChildForm

    def get_context_data(self, **kwargs):
        context = super(ChildrenCreateView, self).get_context_data(**kwargs)
        context['back_url'] = self.request.META.get('HTTP_REFERER', reverse_lazy('children:list'))
        return context


class ChildrenDetailView(ChildBaseView, DetailView):
    template_name = 'children/children_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ChildrenDetailView, self).get_context_data(**kwargs)
        context['params'] = Param.objects.all()
        return context


class ChildrenUpdateView(ChildBaseView, UpdateView):
    template_name = 'children/children_edit.html'
    form_class = ChildForm

    def get_context_data(self, **kwargs):
        context = super(ChildrenUpdateView, self).get_context_data(**kwargs)
        context['back_url'] = \
            self.request.META.get('HTTP_REFERER',
                                  reverse_lazy('children:detail',
                                               kwargs={'children_id': self.object.id}))
        return context


class ChildrenDeleteView(ChildBaseView, DeleteView):

    def get_success_url(self):
        return reverse_lazy('children:list')


class ChildListJson(BaseDatatableView):
    order_columns = ['last_name', 'birthday']

    def __init__(self):
        super(ChildListJson, self).__init__()
        self.date = datetime.now()

    def get_initial_queryset(self):
        return Child.objects.all()

    def filter_queryset(self, qs):
        search = self.request.GET.get(u'search[value]', None)
        _filter = self.request.GET.get(u'columns[0][search][value]', None)

        if _filter:
            children_list = []
            filter_params = json.loads(_filter)

            health_states = []
            mode_health_states = 0
            parents_status = []
            mode_parents_status = 0

            if 'date' in filter_params:
                filter_params['date'] = datetime.strptime(
                    filter_params['date'],
                    '%Y-%m-%dT%H:%M:%S.%fZ'
                )
                self.date = filter_params['date']
            if 'institution' in filter_params:
                qs = get_qs_by_param_name(name='institution', qs=qs, **filter_params)
            if 'group' in filter_params:
                qs = get_qs_by_param_name(name='group', qs=qs, **filter_params)
            if 'grade' in filter_params:
                qs = get_qs_by_param_name(name='grade', qs=qs, **filter_params)
            if 'health_states'in filter_params:
                health_states = get_list_names_in_param(
                    filter_params['health_states'],
                    param='health'
                )
                mode_health_states = filter_params['mode_health_states']
                qs = get_qs_by_param_name(name='health_states', qs=qs, **filter_params)
            if 'parents_status' in filter_params:
                parents_status = get_list_names_in_param(
                    filter_params['parents_status'],
                    param='parents'
                )
                mode_parents_status = filter_params['mode_parents_status']
                qs = get_qs_by_param_name(name='parents_status', qs=qs, **filter_params)

            for child in qs:
                children_list.append([
                    child.id,
                    get_param_on_date(child, 'health', 'health_list', filter_params['date']),
                    get_param_on_date(child, 'parents', 'parents_list', filter_params['date']),
                ])

            if health_states and mode_health_states != 0:

                _children_list = children_list.copy()
                children_list.clear()

                if mode_health_states == 2:

                    _condition = ', '.join([states for states in health_states])
                    for _children in _children_list:
                        if _children[1] == _condition:
                            children_list.append(_children)
                else:

                    _condition = [states for states in health_states]
                    for _children in _children_list:

                        if set(_condition) <= set(_children[1].split(', ')):
                            children_list.append(_children)

                qs = qs.filter(pk__in=set([child[0] for child in children_list]))

            if parents_status and mode_parents_status != 0:

                _children_list = children_list.copy()
                children_list.clear()

                if mode_parents_status == 2:

                    _condition = ', '.join([status for status in parents_status])
                    for _children in _children_list:
                        if _children[2] == _condition:
                            children_list.append(_children)
                else:

                    _condition = [status for status in parents_status]
                    for _children in _children_list:

                        if set(_condition) <= set(_children[2].split(', ')):
                            children_list.append(_children)

                qs = qs.filter(pk__in=list(set([child[0] for child in children_list])))

        if search:

            if search.find(' ') != -1:
                filter_last_name = search.split(' ')[0]
                filter_first_name = search.split(' ')[1]
                qs = qs.filter(last_name__istartswith=filter_last_name,
                               first_name__istartswith=filter_first_name)
            else:
                qs = qs.filter(last_name__istartswith=search)

        return qs

    def prepare_results(self, qs):

        json_data = []

        for item in qs:
            json_data.append(
                {'full_name': item.get_full_name(),
                 'link': item.get_absolute_url(),
                 'age': item.get_age(date=self.date)
                 }
            )
        return json_data

src/apps/common/views.py
# -*- coding: utf-8 -*-
import json

import django_rq
from django.http import HttpResponse
from rq.job import Job


def status_view(request):
    ret = {}
    job_id = request.GET.get('job_id')
    redis_conn = django_rq.get_connection()
    job = Job.fetch(job_id, redis_conn)
    if job.is_finished:
        ret = {'status': 'finished'}
    elif job.is_queued:
        ret = {'status': 'in-queue'}
    elif job.is_started:
        ret = {'status': 'waiting'}
    elif job.is_failed:
        ret = {'status': 'failed'}

    return HttpResponse(json.dumps(ret), content_type="application/json")

src/apps/dictionaries/views.py
from django.views.generic.base import TemplateView
from dictionaries.models import Category

EDIT_TEMPLATE = 'dictionaries/edit.html'


def get_template(template, name):
    return '{}/{}.html'.format(template, name)


class DictionariesView(TemplateView):
    template_name = 'dictionaries/index.html'

    def get_context_data(self, **kwargs):
        context = super(DictionariesView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context

src/apps/example/views.py
from django.shortcuts import render


def home(request):
    context = {
        'hello': 'Hello world'
    }
    return render(request, 'example/index.html', context)

src/templates/children/children_detail.html
{% extends 'children/layout.html' %}
{% load get_params %}

{% block page_header %}
    {{ block.super }}
    <div class="pull-right">
        <a href="{% url 'children:edit' child.id %}" class="btn btn-primary">Редактировать</a>
        <a href="javascript:void(0);" class="btn btn-danger" data-toggle="modal" data-target=".delete-modal"
           onClick='obj_delete("{{ child }}", "{% url 'children:delete' child.id  %}");'>Удалить</a>
    </div>
{% endblock page_header %}


{% block content %}

    {% include 'modals/_modal_delete.html' %}

<div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="panel panel-default">
      <div class="panel-heading">Основные данные</div>
      <ul class="list-group">
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Фамилия</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.last_name }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Имя</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.first_name }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Отчество</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.middle_name }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Дата рождения</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.birthday }}</div>
            </div>
        </li>
      </ul>
    </div>
    </div>

    <div class="col-md-6 col-sm-6">
      <div class="panel panel-default">
      <div class="panel-heading">Адрес</div>
      <ul class="list-group">
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Населенный пункт</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.locality }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Улица</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.street|default:"" }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Дом</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.house }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4 col-xs-4"><strong>Квартира</strong></div>
                <div class="col-md-8 col-xs-8">{{ child.flat }}</div>
            </div>
        </li>
      </ul>
    </div>
    </div>
</div>
{% if params %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs nav-justified" role="tablist">
            {% for param in params %}
            <li role="presentation" {% if forloop.first %}class="active"{% endif %}>
                <a href="#{{ param.slug }}" aria-controls="{{ param.slug }}" role="tab" data-toggle="tab">{{ param.name }}</a>
            </li>
            {% endfor %}
          </ul>

            <!-- Tab panes -->

            <div class="tab-content">
            {% for param in params %}
                <div role="tabpanel" class="tab-pane fade {% if forloop.first %}active in{% endif %}" id="{{ param.slug }}">
                    <h4 class="tab-header">
                        <span class="title title_tab">{{ param.name }}</span>
                        <div class="pull-right">
                            <a href="{% url 'children:history-add' child.id param.slug %}" class="btn btn-primary">Добавить</a>
                        </div>
                    </h4>
                    {% with child.paramhistory_set.all as param_history %}
                        {% get_history child param_history param.slug %}
                    {% endwith %}
                </div>

            {% endfor %}
            </div>

        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

src/templates/children/children_edit.html
{% extends 'children/layout.html' %}
{% load bootstrap  %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-body">
             <form class="form-horizontal" method="post">
                 {% csrf_token %}
                 {{ form | bootstrap_horizontal }}
                 <div class="pull-right">
                    <a href="{{ back_url }}" class="btn btn-default">Отменить</a>
                    <button type="submit" class="btn btn-primary">Выполнить</button>
                 </div>
             </form>
            </div>
        </div>
    </div>
</div>
{% endblock content  %}

src/templates/children/children_list.html
{% extends 'children/layout.html' %}
{% load get_params %}
{% load bootstrap  %}
{% block page_header %}
            {{ block.super }}
            <div class="pull-right">
            <a href="{% url 'children:add' %}" class="btn btn-primary">Добавить</a>
        </div>
{% endblock page_header %}

{% block content %}
<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-filter">
                    {{ filter_form | bootstrap }}
                    <button id="btnFilter" class="btn btn-block btn-primary" type="submit">Показать</button>
                    <button id="btnReset" class="btn btn-block btn-default" type="submit">Сбросить</button>
                </div>

            </div>
        </div>
    </div>

    <div class="col-md-9">

        <div class="panel panel-default">
            <div class="table-responsive">
                <table id="children" class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Ребенок</th>
                            <th>Возраст</th>
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/children/layout.html
{% extends 'layout/content.html' %}
{% load sitetree %}

{% block title %}{% sitetree_page_title from "children" %} |  {{ block.super }}{% endblock title %}

{% block page_header %}
    {% sitetree_page_title from "children" %}
{% endblock page_header %}

{% block breadcrumbs %}
    {% sitetree_breadcrumbs from "children" template "layout/breadcrumbs.html" %}
{% endblock breadcrumbs %}